spring:
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  file:
    upload-dir: ./uploads
    pdf-templates-dir: ./uploads/pdf-templates

jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiration: 864000000 # 24h (ms)


hisnet:
  url: ${HISNET_URL}
  access_key: ${HISNET_ACCESS_KEY}

logging:
  level:
    com.hiswork.backend.service.PdfService: DEBUG
    com.hiswork.backend.controller.DocumentController: DEBUG
    com.hiswork.backend.service.DocumentService: DEBUG
    root: INFO